-- Insert message categories
INSERT INTO message_categories (name) VALUES
('emojis'),
('general'),
('batch'),
('batch2'),
('batch3'),
('batch4'),
('batch5'),
('batch6'),
('batch7'),
('batch8'),
('batch9'),
('batch10'),
('batch11'),
('batch12'),
('batch13'),
('batch14'),
('do_not_send'),
('griffith'),
('kanye'),
('reagan'),
('nick'),
('ksi'),
('mussolini'),
('tate'),
('wakeytime'),
('sleepytime'),
('happy_fucker'),
('upset_fucker'),
('sss_tier_opinions'),
('hello_followup');

-- Insert messages for each category
INSERT INTO messages (category_id, content) VALUES
-- Emojis
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:tomoko_cup:1358095740299116614>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:cirnoarc:1358517895809990793>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:tomokoarc:1358500281956044991>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:depressed:1358517922938617883>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:emoji_52:1358517952311463956>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:tomoko_konata:1358518030547816570>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:tomoko_bread:1358518885829185816>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:tomoko_like:1358518895627210762>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:umarucry:1358518905219584120>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:wtf:1358518914631602449>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:xd:1358518924303667272>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:pekostare:1365786858465919046>'),
((SELECT id FROM message_categories WHERE name = 'emojis'), '<:wholesome:1403161256189493350>'),

-- General
((SELECT id FROM message_categories WHERE name = 'general'), '<:tomoko_cup:1358095740299116614>'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hello watafriends'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/larsandtherealgirl-trailer-ryangosling-newgirlfriend-doll-gif-3525692'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/republican-gif-24490147'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/wesker-resident-evil-5-the-mastermind-dead-by-daylight-project-w-gif-8481201659685876360'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/griffith-berserk-haha-smile-griffith-gif-24652295'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/mads-mikkelsen-smoking-gif-24232377'),
((SELECT id FROM message_categories WHERE name = 'general'), 'From the the screen to the pen to the ring to the king'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/dont-care-go-my-metal-sonic-metal-sonic-sonic-cd-knuckles-chaotix-go-metal-sonic-gif-5455408462557000696'),
((SELECT id FROM message_categories WHERE name = 'general'), 'You are so based yeezy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/anime-berserk-griffith-necklace-off-gif-17645086'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Me whit tomoko doll'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am prime Griffith'),
((SELECT id FROM message_categories WHERE name = 'general'), '<:cirnoarc:1358517895809990793>'),
((SELECT id FROM message_categories WHERE name = 'general'), '<:tomokoarc:1358500281956044991>'),
((SELECT id FROM message_categories WHERE name = 'general'), '<:depressed:1358517922938617883>'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/minion-gooning-gym-smoking-nevergoon-gif-16345362028907877022'),
((SELECT id FROM message_categories WHERE name = 'general'), 'She know that i am a bully'),
((SELECT id FROM message_categories WHERE name = 'general'), 'She Wanna Hop in a rari'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Preacherman an rari are +SSS Tier songs'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/persona-persona3-minato-arisato-makoto-yuki-battle-gif-17813346'),
((SELECT id FROM message_categories WHERE name = 'general'), '-9999 watapoints'),
((SELECT id FROM message_categories WHERE name = 'general'), 'average sonic fan ⬆️'),
((SELECT id FROM message_categories WHERE name = 'general'), 'least schizo sonic fan'),
((SELECT id FROM message_categories WHERE name = 'general'), 'lain red pill aura'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I want watamote movie someday'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/touhou-cirno-pumped-excited-punch-gif-17552731'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/tomoko-kuroki-gif-25980950'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Send csgo clips'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/smoking-duck-dj-khaled-what-does-he-even-do-gif-8004262131450496811'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Wataland = falconia'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Lain should Nuke all'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am rightchad'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Alt right chad'),
((SELECT id FROM message_categories WHERE name = 'general'), 'im based rightchad'),
((SELECT id FROM message_categories WHERE name = 'general'), 'i am a right chad'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/springtrap-gif-22758628'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/fumo-ayumu-kasuga-osaka-cirno-azumanga-daioh-gif-20739417'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Silent Hill  tesla'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Lain=Akira'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Le Ferrari F8 Lamborghini roadster'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/pepe-popcorn-pepe-pepe-frog-frog-meme-pepe-gif-13771789960385103599'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/azumanga-daioh-osaka-osaker-speech-gif-12106132575117515996'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/patrick-bateman-gif-26282297'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/incel-wojak-meme-anime-glasses-gif-21218188'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/yay-yippee-clap-fuuka-yamagishi-gif-11473661067883569119'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/kanye-west-kanye-ye-vultures-vultures-1-gif-16466379573931117087'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hail Mussolini'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Mark my words meeper'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Meeper how you do?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Whats your secret meeper'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Ahahahahah'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hahahahaa'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/back-to-the-future-ronald-gif-21233116'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/based-metal-gear-metal-gear-solid-big-boss-venom-snake-gif-21735928'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/squirtle-pokemon-gif-23882585'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/postal-postal-dude-breaking-bad-walter-white-meme-gif-26851972'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/vultures-vultures-1-kanye-west-ye-yeezy-gif-14661580508021642873'),
((SELECT id FROM message_categories WHERE name = 'general'), 'How I''m anti-Semitic?\nI just fucked a Jewish bitch\nI just fucked Scooter''s bitch and we ran her like Olympics\nGot pregnant in the threesome, so whose baby is it?\nWhose baby is it?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/ronald-reagan-its-a-great-feeling-1949-well-well-well-jack-curtiz-in-person-barber-shop-gif-21273551'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/tomoko-watamote-tomoko-kuroki-kuroki-dance-gif-3529097142210118205'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Lain>Cthulhu'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/lain-sel-serial-experiments-lain-iwakura-silly-gif-26865566583074851370'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/berserk-griffith-smile-gif-26958203'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Boy dont play whit me you know i am fried'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/griffith-berserk-seinen-manga-manga-seinen-gif-16052926'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/pokemon-pokeani-anipoke-pokemon-horizons-shuckle-gif-1434229247519097369'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://youtu.be/4DmnuewuOws'),
((SELECT id FROM message_categories WHERE name = 'general'), 'New Kanye song Is wild'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Danganropa Kanye west'),
((SELECT id FROM message_categories WHERE name = 'general'), 'i am spittin venom'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I''m spittin'' out venom'),
((SELECT id FROM message_categories WHERE name = 'general'), 'God of falconia AND  wataland'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Too much money to be in the streets\nToo much money to spend all on me\nToo much hate and not enough love\nFree Larry, free Young Thug\nFree Larry, free Young Thug'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Shuckle hang whit arceus'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Arceus Nuke type wold be broken'),
((SELECT id FROM message_categories WHERE name = 'general'), 'What if Miku appear in watamote movie ?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Miku house'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Miku town'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Miku country someday who knows'),
((SELECT id FROM message_categories WHERE name = 'general'), 'CAT bird pog\nPeak of evolution\n1- Cirno \n2- CAT bird \n3- DOG bird'),
((SELECT id FROM message_categories WHERE name = 'general'), 'NHH'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hello Gods'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Kanye drop Cuck album'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Normal Tomoko silver Tomoko vultures Tomoko'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Free Diddy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Kanye music'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Lain at my side'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Osaka Wanna Hop in a rari'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hello citizens of wataland falconia'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Also neco Arc  in fornite wold be crazy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Yeezy in fornite'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Osaka Bein Kanye fan Is canon'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/berserk-gif-2898366366016578155'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/femto-griffith-berserk-manga-anime-gif-14902110100260594587'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Gonna run for president someday'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Shhhhhhh i am listening preacherman'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Tomoko whit a vultures shirt in fornite someday'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nuke all'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Lain pls'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/hatred-gun-edgy-gif-18213167'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nitrous really fucked whit my  brain'),
((SELECT id FROM message_categories WHERE name = 'general'), 'She eat my kids like jared'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://youtu.be/2RdI94t0FXQ'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am a God'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Thanks Reagan  now we have cat birds'),
((SELECT id FROM message_categories WHERE name = 'general'), 'The free world won'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Pubg'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am ye fan'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Catbirds are a thing because of Reagan you know?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nitrous really fucked my head'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Watamote season two Is the one piece'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Maybe Tomoko Is the one piece the best friend that someone can have'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Alabamian pancakes'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Reagan wold say vultures 2 Is goated'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Reagan wold say he have redneck aura'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Gonna rock a swastika Chain someday as my goat'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Kanye west Cousin song'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I hig diff Sonic.exe\nAlso all scp'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I solo all'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Summon Tails.exe'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Based'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://www.youtube.com/watch?v=S2Q8hVhoCKU'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://www.youtube.com/watch?v=gZsX4hY_XxE'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am in love whit the nitrous'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I''m in love whit the nitrous'),
((SELECT id FROM message_categories WHERE name = 'general'), 'While i try be king as shuckle the third'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nuke china'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Gonna rule all someday\nAs Kanye west the goat'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nuke china from the Dam orbit\nSimple as that'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am Alien X'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hello\nCitizens of Wataland\nFalconia'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am european hooligan in my Hart'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Black Yoshi nukin luigi'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hello guys'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Tomoko haters irl\nRats'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Buy a gun better'),
((SELECT id FROM message_categories WHERE name = 'general'), 'America number 1'),
((SELECT id FROM message_categories WHERE name = 'general'), 'USA USA USA'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nukes for all'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hitler ye and jesuschrist'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Listening Hitler ye and jesuschrist rn'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Also listening rn Hitler ye and jesuschrist'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hitler ye an jesuschrist'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am Griffith in wataland'),
((SELECT id FROM message_categories WHERE name = 'general'), 'All caps ANDREW GOD'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Wataland kingdom of falconia'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Alabama best state'),
((SELECT id FROM message_categories WHERE name = 'general'), 'She like my nazi vibes\nShe now i am a bully'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Andrew lore'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nazi vibes'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/griffith-dream-castle-gif-14434716816546279906'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am from alabama'),
((SELECT id FROM message_categories WHERE name = 'general'), 'dirty magazines\nhttps://www.youtube.com/watch?v=bPLw76nn7FQ'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://www.youtube.com/watch?v=Yt3PB2GiLeU'),
((SELECT id FROM message_categories WHERE name = 'general'), 'slavs be like'),
((SELECT id FROM message_categories WHERE name = 'general'), 'russia will win'),
((SELECT id FROM message_categories WHERE name = 'general'), 'average mugen fight'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/nightcrawler-sunglasses-nightcrawler-sunglasses-jake-gyllenhaal-gif-22726772'),
((SELECT id FROM message_categories WHERE name = 'general'), 'moon man bus'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/american-psycho-smoke-sigma-gif-26186111'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/cirno-cirno-fumo-fumo-gif-21728275'),
((SELECT id FROM message_categories WHERE name = 'general'), 'i want be purple guy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/purpleguy-gif-18453568'),
((SELECT id FROM message_categories WHERE name = 'general'), 'what if joeyworld tour become purple guy in the movie'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/himouto-umaru-chan-cute-anime-christmas-happy-gif-16094038'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Probably that video Is trolling'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nah i dont think as destiny but that''s legit trolling for sure'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Osaka troll hard this Time wtf'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Tell me that''s water\nPls'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hello everynian'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Listening cousins rn'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Gonna have the red Button someday'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I Wanna fuck summ right now'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/major-hellsing-hellsing-ultimate-millennium-montana-max-gif-13043360951041944448'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Ash Williams Is a rightchad\nHe wold Nuke all an then drink a beer for sure'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Also Tomoko should be in Mario kart world\nAlso the goomba'),
((SELECT id FROM message_categories WHERE name = 'general'), 'a''int gonna sleep until see Tomoko in Mario kart'),
((SELECT id FROM message_categories WHERE name = 'general'), 'You think Tomoko Will be in Mario kart world someday?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'she like Kanye west music?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Aldi Aldi Aldi'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Wanna join my ship?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Where the Tomoko car?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Watamote SSS+ manga\nAlso  that one of the vampire guy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'hell nah i am mario bros enjoyer'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/gifmurloc-aga-gifmurloc-gif-18024839'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Tomo city pog'),
((SELECT id FROM message_categories WHERE name = 'general'), 'the fall of the berlin wall\nthe victory over the soviets'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/nite-owl-herolanding-watchman-gif-18353942'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/dr-manhattan-gif-10480909'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Nuke france'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am antisemetic fully'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am antisemetic fully\nUsing swastikas couse all my niggaa nazis'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/murloc-flesheater-warcraft3-wc3-avatar-gif-15258162'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://www.youtube.com/shorts/C5yMROQpfRA'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Based\nSnyder Superman wold Nuke all for sure\nDead God moment'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am a monster'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Ice cream cat'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Alien X aura'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Couse i am a villain Also a pirate\nLike Kanye west'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Andrew Wanna be my left hand but that''s trinke\nMy own schizoprenia can''t be my lefthand'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Low Tier God'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I start running backwards i was too fast'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Gonna be the LTG fishticks'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Maybe someday Miku Also Will get a fishticks skin'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Gonna get the Raiden taunt to be like ltg in fornite'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/ltg-gif-40123618314459872'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Touhou drink'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Fish'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Those who know'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/troll-trollface-scary-void-scary-troll-face-gif-19777211'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Brainrot'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Duck'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Void meme'),
((SELECT id FROM message_categories WHERE name = 'general'), 'All admire my nazi vibes'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/n-h-h-hh-ah-kanye-west-gif-3605193572459858796'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/giancarlo-esposito-smoking-far-cry6-ant%C3%B3n-castillo-gif-26151971'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Go Griffith'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Postal guy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Schizo bunny'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Sonic.exe did me wrong'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I kill the server\nWhit my schizoprenia'),
((SELECT id FROM message_categories WHERE name = 'general'), 'The one piece\nAndrew nazi king of the pirates'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Quit league'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Why mango?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Mango?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I can be a tyrant an respect woman right?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Where Alien X phonk?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I like cherries'),
((SELECT id FROM message_categories WHERE name = 'general'), 'AI Is wild'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Crash supremacy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/crash-bandicoot-2-gif-10703865519411988560'),
((SELECT id FROM message_categories WHERE name = 'general'), 'American dad Is better obviusly'),
((SELECT id FROM message_categories WHERE name = 'general'), 'This place Is based'),
((SELECT id FROM message_categories WHERE name = 'general'), 'cats are goated'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Playboi cartiii 🗣️🔥🔥🔥🔥'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/playboi-carti-playboi-carti-dancecarti-gif-1369910845517190782'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Im in the thick of it everbody knows\nThey know me where it snows'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hangin whit cousins reading dirty magazines'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/hidamari-sketch-miyako-miya-wide-gif-26443809'),
((SELECT id FROM message_categories WHERE name = 'general'), 'go to alabama'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/sam-and-max-sam-%26-max-spin-spinning-funny-gif-5568239150402824677'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/doomer-ken-kanye-fan-gif-25334451'),
((SELECT id FROM message_categories WHERE name = 'general'), 'i am a soy'),
((SELECT id FROM message_categories WHERE name = 'general'), 'KFC SSS+ Tier'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Freddy fazbear pizza SSSS+ Tier'),
((SELECT id FROM message_categories WHERE name = 'general'), 'make cirno'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Finally lobotomy watafriends'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Playing whit the blocks like tetris'),
((SELECT id FROM message_categories WHERE name = 'general'), 'She ride my Dick like a carnival'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/santam-hooligans-gif-21973387'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Watamote  enjoyers'),
((SELECT id FROM message_categories WHERE name = 'general'), 'aint in a lonely feeling Bein just me'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Waiting the Collab of joeyworldtour and Tomoko'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/tomoko-kuroki-watamote-danapilled-gif-25692075'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Niggas a''int gonna sleep until see Diddy free'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://youtu.be/cjjh-pc-qHQ?si=iyv3UmNnejskaEiG'),
((SELECT id FROM message_categories WHERE name = 'general'), 'What if Tomoko joins smash bros?'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Certified watamote fan certified rightchad'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Tomoko ult wold be grab ak an shoot all'),
((SELECT id FROM message_categories WHERE name = 'general'), 'They dont understand the shit i say in twitter\nNigga\nHH'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Not hiding anymore my nazi vibes'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Goin to smash bros whit this one'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://youtu.be/lLOBedFymoA?si=vWc1IytVhn05PJmf'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am Sonic.exe'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Hangin whit my cousin reading dirty magazines'),
((SELECT id FROM message_categories WHERE name = 'general'), 'The Man behind the slaugther'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/springtrap-fire-fnaf-gif-2873982408042466685'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am Shadow bunny'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/fnaf-get-real-nikolai-nikolaialberdi-shadow-bonnie-gif-19527847'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Persona 🗣️🔥'),
((SELECT id FROM message_categories WHERE name = 'general'), 'My new persona Is Shadow bunny'),
((SELECT id FROM message_categories WHERE name = 'general'), 'https://tenor.com/view/shadow-bonnie-fnaf-fnaf2-toy-bonnie-gif-22177468'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Fnaf Lore two guys whit a crazy idea'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am a mistery'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I am the shadow'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Ashleeey'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Watafriends a''int gonna sleep until see watamote season two'),
((SELECT id FROM message_categories WHERE name = 'general'), 'I''m triying fuck sumn rn'),
((SELECT id FROM message_categories WHERE name = 'general'), '🗣️ 🔥 🔥 🔥 🔥 Play boi cartiiii'),
((SELECT id FROM message_categories WHERE name = 'general'), '🗣️🔥🔥🔥🔥 Travis Scott'),
((SELECT id FROM message_categories WHERE name = 'general'), 'Alabamian cousine'), -- ./media/alabamachicken.jpg
((SELECT id FROM message_categories WHERE name = 'general'), 'SSS+ burger from alabama\nAlso alabamian tomatoe'), -- ./media/alabamaburger.jpg
((SELECT id FROM message_categories WHERE name = 'general'), NULL), -- Attachments without text

-- Batch
((SELECT id FROM message_categories WHERE name = 'batch'), 'I think i am kinda incel and blackpilled'),
((SELECT id FROM message_categories WHERE name = 'batch'), 'Sorry all'),
((SELECT id FROM message_categories WHERE name = 'batch2'), 'lain power: nuke'),
((SELECT id FROM message_categories WHERE name = 'batch2'), 'https://tenor.com/view/serial-experiments-lain-lain-anime-smug-anime-smile-gif-14038034'),
((SELECT id FROM message_categories WHERE name = 'batch3'), 'Watamote movie can be a crossover whit azumanga dahio'),
((SELECT id FROM message_categories WHERE name = 'batch3'), 'What you guys think about this'),
((SELECT id FROM message_categories WHERE name = 'batch4'), 'https://tenor.com/view/kanye-west-kanye-ye-vultures-vultures-1-gif-16466379573931117087'),
((SELECT id FROM message_categories WHERE name = 'batch4'), 'This Is crazy so well made'),
((SELECT id FROM message_categories WHERE name = 'batch5'), 'Someday gonna rock a swastika diamond chain'),
((SELECT id FROM message_categories WHERE name = 'batch5'), 'As Kanye west the goat'),
((SELECT id FROM message_categories WHERE name = 'batch6'), 'Kanye new music Is good'),
((SELECT id FROM message_categories WHERE name = 'batch6'), 'Cousins'),
((SELECT id FROM message_categories WHERE name = 'batch6'), 'Free diddy'),
((SELECT id FROM message_categories WHERE name = 'batch6'), 'Cosby'),
((SELECT id FROM message_categories WHERE name = 'batch6'), 'Top Tier SSS+ songs'),
((SELECT id FROM message_categories WHERE name = 'batch6'), 'Also nitrous'),
((SELECT id FROM message_categories WHERE name = 'batch7'), 'Yes i am a mad God'),
((SELECT id FROM message_categories WHERE name = 'batch7'), 'I am evil'),
((SELECT id FROM message_categories WHERE name = 'batch7'), 'As Kanye west the great'),
((SELECT id FROM message_categories WHERE name = 'batch8'), 'Watafriends power level top\n1- hellbey God\n2- lain\n3- Alien X  Andrew total  control\n4-Tomoko\n5- Andrew femto form\n6- trinke God\n7- Kanye west 1% of power\n8- Andrew bot Is a chaotic force too be recognize'),
((SELECT id FROM message_categories WHERE name = 'batch8'), 'Drago Is close to lain place 2 power he create  Andrew bot\nPeanut goddes Is at top 2 as lain'),
((SELECT id FROM message_categories WHERE name = 'batch8'), 'To use my Alien X form at total control i need to talk to the voices that''s why i am top 3 i am at top 10 in my normal form\nBasically murloc npc'),
((SELECT id FROM message_categories WHERE name = 'batch8'), 'Also you see the power tierlist ?\nThougs?'),
((SELECT id FROM message_categories WHERE name = 'batch9'), 'Literally me\nIn school years ago'),
((SELECT id FROM message_categories WHERE name = 'batch9'), 'Then i become edgy\nThen a discord owner\nThen a ex discord owner'),
((SELECT id FROM message_categories WHERE name = 'batch9'), 'Then SpookedDoor become my right hand\nThen Trump won\nHappy history'),
((SELECT id FROM message_categories WHERE name = 'batch10'), 'I wannabe a tyrant'),
((SELECT id FROM message_categories WHERE name = 'batch10'), 'To rule all'),
((SELECT id FROM message_categories WHERE name = 'batch10'), 'I can be a tyrant an respect woman right?'),
((SELECT id FROM message_categories WHERE name = 'batch11'), 'I am a God like Sonic.exe'),
((SELECT id FROM message_categories WHERE name = 'batch11'), 'We should envite that Sonic here'),
((SELECT id FROM message_categories WHERE name = 'batch11'), 'Sonic.exe in watafriends'),
((SELECT id FROM message_categories WHERE name = 'batch11'), 'Legendary crossover'),
((SELECT id FROM message_categories WHERE name = 'batch11'), 'https://tenor.com/view/banner-gif-25494268'),
((SELECT id FROM message_categories WHERE name = 'batch12'), 'You wish to be me'),
((SELECT id FROM message_categories WHERE name = 'batch12'), 'For sure'),
((SELECT id FROM message_categories WHERE name = 'batch12'), 'The God'),
((SELECT id FROM message_categories WHERE name = 'batch12'), 'The glorious one'),
((SELECT id FROM message_categories WHERE name = 'batch13'), 'oh the misery'),
((SELECT id FROM message_categories WHERE name = 'batch13'), 'everybody wants to be my enemy'),
((SELECT id FROM message_categories WHERE name = 'batch13'), 'even incels cant againts me'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'As i say'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'Murlocs should be in fornite'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'Also Alien X'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'An lain'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'An Mario bros'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'An Sonic.exe'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'Also tails.exe'),
((SELECT id FROM message_categories WHERE name = 'batch14'), 'Guys  Toughs on murlocs?'),
((SELECT id FROM message_categories WHERE name = 'do_not_send'), 'User message: https://tenor.com/view/the-simpsons-bart-shock-electric-chair-gif-12706212\nAndrew''s response: Me after lobotomy'),
((SELECT id FROM message_categories WHERE name = 'do_not_send'), 'User message: Banana-drew\nAndrew''s response: Pog my own animatronic nickname\nA monkey animatronic from alabama'),
((SELECT id FROM message_categories WHERE name = 'do_not_send'), 'User message: ezgif-7-f82d4a7d07.gif\nAndrew''s response: Tomoko haters irl\nRats'),
((SELECT id FROM message_categories WHERE name = 'do_not_send'), 'Alabamian cousine'),
((SELECT id FROM message_categories WHERE name = 'do_not_send'), 'SSS+ burger from alabama\nAlso alabamian tomatoe'),

-- Wakey time
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'morning all i am Griffith'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'morning all i am Griffith'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'morning all i am Griffith'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'Good morning'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'Morning'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'Good morning uh uh uh'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'Morning all'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'Hello everynian'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'https://tenor.com/view/griffith-berserk-good-morning-good-morning-chat-hello-chat-gif-7712373713074364619'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'https://tenor.com/view/whale-shark-good-morning-gm-good-night-gn-gif-26569624'),
((SELECT id FROM message_categories WHERE name = 'wakeytime'), 'https://tenor.com/view/kanye-fuzzle-good-morning-gif-26126244'),

-- Sleepy time
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all i am Griffith'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all i am Griffith'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all i am Griffith'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all dream whit wataland falconia'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all dream whit Kanye west'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Gn all friends of wataland'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Gn'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN guys'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'gn friends'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'https://tenor.com/view/sleep-gif-16267239586470775658'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Gn watafriends'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Gn all watafriends'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'gn tomoko fan club'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN knights'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all dream whit tomboy  cirno'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'https://tenor.com/view/gypsy-crusader-gypsy-joker-gn-gif-23761746'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'https://tenor.com/view/osaka-azuman-goodnight-gn-sleep-gif-24066064'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Goodnight kingdom of wataland falconia'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'https://tenor.com/view/griffith-berserk-griffith-good-night-griffith-griffithlvr-berserk-gif-18377682904186629085'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'https://tenor.com/view/griffith-berserk-good-night-chat-bye-chat-goodbye-chat-gif-4987401896551940413'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'https://tenor.com/view/osaka-azumanga-daioh-ayumu-kusaga-ayumu-good-night-gif-961306308588708616'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Gn all dream whit me Bein the world ruler'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Gn all dream whit me as a God'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN commies'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN liberals'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN murloc enjoyers'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'GN all\nDream whit tomoko using the behelit'),
((SELECT id FROM message_categories WHERE name = 'sleepytime'), 'Good night all\nDream whit me as the supreme Lord emperor of falconia'),

-- Griffith
((SELECT id FROM message_categories WHERE name = 'griffith'), 'I am prime Griffith'),
((SELECT id FROM message_categories WHERE name = 'griffith'), 'I am Femto God'),
((SELECT id FROM message_categories WHERE name = 'griffith'), 'I am Griffith in wataland'),
((SELECT id FROM message_categories WHERE name = 'griffith'), 'I am Griffith God'),
((SELECT id FROM message_categories WHERE name = 'griffith'), NULL), -- Attachments without text

-- Kanye
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye the goat'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I love Kanye'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye will drop new album'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'new kanye interview'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Like new Kanye album?'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'This aint cheddar this quiche'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I hang whit the vultures'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'You like vultures also?'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I like vultures'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Vultures 2 is goated'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I got all to hang whit the vultures'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://tenor.com/view/kanye-west-vultures-everybody-new-gif-12847039774498163445'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://tenor.com/view/ye-kanye-kanye-vultures-vultures-listening-party-vultures-lp-gif-14111380029791063141'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://tenor.com/view/kanye-west-gif-1846075065280866456'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://tenor.com/view/kanye-west-kanye-ye-um-uhm-gif-1371611536126645899'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://tenor.com/view/kanye-west-my-reaction-to-that-information-my-honest-reaction-meme-gif-15000744814966995138'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye Goat'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'New Kanye song Is wild'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Danganropa Kanye west'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye drop Cuck album'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye music'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Free Diddy'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Diddy Is good rapper Also kanye'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Yeezy in fornite'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Osaka Bein Kanye fan Is canon'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Shhhhhhh i am listening preacherman'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Tomoko whit a vultures shirt in fornite someday'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I am ye fan'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://www.youtube.com/watch?v=gZsX4hY_XxE'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Nitrous really fucked whit my  brain'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'She eat my kids like jared'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://youtu.be/2RdI94t0FXQ'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Nitrous really fucked my head'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://www.youtube.com/watch?v=S2Q8hVhoCKU'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye plays 69D chess whit all'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye west'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I am evil As Kanye west the great'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye new music Is good'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Someday gonna rock a swastika diamond chain As Kanye west the goat'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Hitler ye and jesuschrist'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Hitler ye an jesuschrist'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Listening Hitler ye and jesuschrist rn'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Also listening rn Hitler ye and jesuschrist'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Gonna rule all someday\nAs Kanye west the goat'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I am in love whit the nitrous'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'I''m in love whit the nitrous'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Reagan wold say vultures 2 Is goated'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Gonna rock a swastika Chain someday as my goat'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Boy dont play whit me you know i am fried'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'You are so based yeezy'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'How I''m anti-Semitic?\nI just fucked a Jewish bitch\nI just fucked Scooter''s bitch and we ran her like Olympics\nGot pregnant in the threesome, so whose baby is it?\nWhose baby is it?'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Too much money to be in the streets\nToo much money to spend all on me\nToo much hate and not enough love\nFree Larry, free Young Thug\nFree Larry, free Young Thug'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'She know that i am a bully'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'She Wanna Hop in a rari'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Preacherman an rari are +SSS Tier songs'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'dirty magazines'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Kanye new music Is good\nCousins\nFree diddy\nCosby\nTop Tier SSS+ songs\nAlso nitrous'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'She like my nazi vibes\nShe now i am a bully'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://www.youtube.com/watch?v=bPLw76nn7FQ'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'https://www.youtube.com/watch?v=Yt3PB2GiLeU'),
((SELECT id FROM message_categories WHERE name = 'kanye'), 'Listening cousins rn'),

-- Reagan
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan was the best'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan number 1'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan number 1 president ever'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan turn down the wall'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Trump and Reagan goats'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan and Trump best presidents ever'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Ronald pls'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'https://tenor.com/view/republican-gif-24490147'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'https://tenor.com/view/ronald-reagan-reagan-republican-usa-president-gif-14605911613553531779'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'https://youtu.be/4DmnuewuOws'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan wold say i win again couse i am the goat as president'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Thanks Reagan  now we have cat birds'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Catbirds are a thing because of Reagan you know?'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan SSS+ president'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan wold say vultures 2 Is goated'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan wold say he have redneck aura'),
((SELECT id FROM message_categories WHERE name = 'reagan'), 'Reagan Top Tier SSS+ president'),

-- Nick Fuentes
((SELECT id FROM message_categories WHERE name = 'nick'), 'nick fuentes is straight'),
((SELECT id FROM message_categories WHERE name = 'nick'), 'https://tenor.com/view/nick-fuentes-fuentes-nicholas-j-fuentes-is-for-me-me-gif-3856804053130586186'),
((SELECT id FROM message_categories WHERE name = 'nick'), 'https://tenor.com/view/fuentes-shooting-you-are-fun-gif-1701233573689015350'),

-- KSI
((SELECT id FROM message_categories WHERE name = 'ksi'), 'ksi is based'),
((SELECT id FROM message_categories WHERE name = 'ksi'), 'ksi is funny'),
((SELECT id FROM message_categories WHERE name = 'ksi'), 'from the screen to the ring to the pen to the king'),
((SELECT id FROM message_categories WHERE name = 'ksi'), 'https://youtu.be/At8v_Yc044Y'),
((SELECT id FROM message_categories WHERE name = 'ksi'), 'https://tenor.com/view/from-the-screen-to-the-ring-the-the-pen-to-the-king-ksi-gif-12257927774644906851'),

-- Mussolini
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'Hail Mussolini'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'You like Mussolini?'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'https://tenor.com/view/benito-mussolini-gif-26264823'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'https://tenor.com/view/benito-mussolini-keep-talking-talking-mad-gif-15512602'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'Like Mussolini? Pog'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'https://tenor.com/view/mussolini-chad-gif-1828092016728334367'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'What why Mussolini Is the best'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'harry Potter and mussolini vs random slav country'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'https://tenor.com/view/mussolini-speech-gif-2561627433093724979'),
((SELECT id FROM message_categories WHERE name = 'mussolini'), 'https://tenor.com/view/mussolini-serious-who-cares-gif-5388395'),

-- Tate
((SELECT id FROM message_categories WHERE name = 'tate'), 'Andrew tate'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'I relate to Andrew tate'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'Andrew Tate skin also'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'Andrew Tate Is free'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'Andrew Tate Is the best'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'I support Andrew Tate'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'He fucked because Andrew Tate say he Will never suicide'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'Soros want kill Andrew tate'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'https://tenor.com/view/andrew-tate-cigar-walking-smoking-andrew-tate-smoking-gif-8005378695551356263'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'https://tenor.com/view/andrew-tate-top-g-cigar-smoking-andrew-tate-cigar-gif-26262606'),
((SELECT id FROM message_categories WHERE name = 'tate'), 'https://tenor.com/view/andrew-tate-gif-26316329');